language: c

branches:
  only:
    - master 

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

addons:
  apt:
    packages:
      - texlive
      - octave
      - octave-pkg-dev
      - qttools5-dev-tools
      - libqt5sql5-sqlite

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1

before_install:
  # Don't do brew update; it takes forever (like five minutes)
  # Ugh; maybe we have to do this to get a fresh enough texinfo
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade texinfo; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install octave; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  #- |
  #  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
  #    sudo apt-get update
  #    sudo apt-get install octave octave-pkg-dev texlive qttools5-dev-tools libqt5sql5-sqlite
  #  fi

script:
  - make local
  # We only build the docs on Linux because it requires TeX and the macOS TeX install is a monster
  # We only need the doc build for verifying doc changes anyway; we don't need multi-platform
  # artifacts, or even the new artifacts at all.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd doc && make maintainer-clean && make all); fi
  - ./dev-tools/runtests.sh inst
  - make dist
