branches:
  only:
    - master

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install octave; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install octave; fi

script:
  - make local
  - octave --path="$PWD/inst" --eval="runtests('inst')"