branches:
  only:
    - master

os:
  - linux
  - osx
dist: xenial
group: travis_latest

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install octave; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install octave octave-pkg-dev texlive; fi

script:
  - cat Makefile
  - find .
  - cat ./dev-tools/runtests.sh
  - make local
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd doc && make all); fi
  - ./dev-tools/runtests.sh inst
  - make dist