language: c

branches:
  only:
    - master 

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

os:
  - linux
  - osx
dist: xenial
group: travis_latest

before_install:
  #- |
  #  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
  #    brew update
  #    time brew upgrade
  #    brew install octave qt
  #  fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install octave; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get update
      sudo apt-get install octave octave-pkg-dev texlive qttools5-dev-tools libqt5sql5-sqlite
    fi

script:
  - make local
  # We only build the docs on Linux because it requires TeX and the macOS TeX install is a monster
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd doc && make all); fi
  - (cd doc && make maintainer-clean && make all)
  - ./dev-tools/runtests.sh inst
  - make dist
